### PR TITLE
Spanish Translation Review

### PR DESCRIPTION
**Pull request by lh1008**
Hi @rehrar, I've been working in a spanish translation for the Monero Revuo. I created a branch called Translation. Hope this is the correct way on working. I also have been working with ErCiccione in the monero localization group and have learned how to work with github(I'm still are...). I was the same guy from last year who told you that was interested in working on spanish translations. Hope you remember. If you have any comments please let me know. Thank you for all your work. :)

### CODE REVIEW

**Comment by rehrar** [comment]
Anything else that needs to be done for this to be merged?

**Comment by lh1008** [comment]
The translation needs reviewing. I will be adding the pdf file during the day. Just adding the images.

**Comment by lh1008** [comment]
Hi @rehrar, I found some spelling mistakes and made the corrections. Also, we(spanish community) have been working on the monero terminology for coherent translations, so I made some changes in the latest update. Hope everything is okay :).

**Comment by lh1008** [comment]
Hi @erciccione,

Was taking a look at the PR and the Monero Ecosystem - Revuo Monero branch and it has not been updated with the pdf and .sla file translation. I'm just leaving you a reminder about these files so they can be reviewed by any other contributor, or if the can be merged with the Revuo Monero so anyone can see the files and use them. I'm not sure if I need to do anything else. Thanks :).

**Comment by erciccione** [comment]
I'm not sure of what you mean @lh1008 , i see the files correctly. What we need is @rehrar to merge this PR to update them

**Comment by lh1008** [comment]
Thank you @erciccione, I thought you were the one who had to merge those files. Sorry. I will keep up with @rehrar the merging of these files. Thank you. :)

**Comment by lh1008** [comment]
Thank you @rehrar, sorry for the pressure. I thought there was something missing out. :) Great day!

**Pull request merged**
